apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version}}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.containerPort}}
  type: {{ .Values.service.type }}